spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    hikari:
      auto-commit: off
    password: 14271915
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres










